# FROM node:16-alpine
# WORKDIR '/app'
# COPY ./package.json ./
# RUN npm install
# COPY . .
# CMD ["npm", "run", "start"]


# pull the base image
FROM node:alpine

# set the working direction
WORKDIR /app

# add /app/node_modules/.bin to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./

COPY package-lock.json ./

# add app
COPY . ./

RUN npm install


# start app
CMD ["npm", "start"]